
name: cgat-report

channels:
- bioconda
- conda-forge
- defaults

dependencies:
# system dependencies
- nomkl
- zlib
- libpng
- pip
# python dependencies
- pyyaml
- python
- docutils
- future
- matplotlib-venn
- matplotlib
- nose
- numpy
- openpyxl
- pandas
- pep8
- pillow
- plotnine
- scipy
- seaborn
- six
- sphinx
- sqlalchemy
- sqlite
- pip:
  - sphinx-tabs
