---
paths:
  home: "/"
  __genindex.html: "/genindex.html"
  __search.html: "/search.html"
  __modindex.html: "/modindex.html"
  __contents.html: "/contents.html"
  __examples__rnaseq__contents.html: "/examples/rnaseq/contents.html"
  __index.html: "/index.html"
  __py-modindex.html: "/py-modindex.html"
  __gallerystatus.html: "/GalleryStatus.html"
  __reference.html: "/Reference.html"
  __gallerytables.html: "/GalleryTables.html"
  __transformations.html: "/Transformations.html"
  __galleryslideshowplot.html: "/GallerySlideShowPlot.html"
  __gallerylineplots.html: "/GalleryLinePlots.html"
  __galleryggplot.html: "/GalleryGGPlot.html"
  __galleryseaborndensityplots.html: "/GallerySeabornDensityPlots.html"
  __galleryrplots.html: "/GalleryRPlots.html"
  __usecase.html: "/UseCase.html"
  __introduction.html: "/Introduction.html"
  __gallerymatrices.html: "/GalleryMatrices.html"
  __galleryseabornheatmapplots.html: "/GallerySeabornHeatmapPlots.html"
  __galleryhistograms.html: "/GalleryHistograms.html"
  __glossary.html: "/Glossary.html"
  __datatypes.html: "/DataTypes.html"
  __gallerybarplots.html: "/GalleryBarplots.html"
  __tutorial8.html: "/Tutorial8.html"
  __gallerydataframe.html: "/GalleryDataframe.html"
  __galleryseaborn.html: "/GallerySeaborn.html"
  __gallerypieplots.html: "/GalleryPiePlots.html"
  __galleryscatterplots.html: "/GalleryScatterPlots.html"
  __server.html: "/Server.html"
  __trackersold.html: "/TrackersOld.html"
  __overview.html: "/Overview.html"
  __tutorials.html: "/Tutorials.html"
  __running.html: "/Running.html"
  __utilities.html: "/Utilities.html"
  __advanced.html: "/Advanced.html"
  __background.html: "/Background.html"
  __complexdocuments.html: "/ComplexDocuments.html"
  __tracker.html: "/Tracker.html"
  __unicode.html: "/Unicode.html"
  __tipstricks.html: "/TipsTricks.html"
  __examples.html: "/Examples.html"
  __roadmap.html: "/Roadmap.html"
  __datamapping.html: "/DataMapping.html"
  __faq.html: "/FAQ.html"
  __developing.html: "/Developing.html"
  __test.html: "/Test.html"
  __errors.html: "/Errors.html"
  __galleryconfig.html: "/GalleryConfig.html"
  __renderers.html: "/Renderers.html"
  __gallerydebug.html: "/GalleryDebug.html"
  ___sources__contents.txt: "/_sources/contents.txt"
  ___sources__gallerystatus.txt: "/_sources/GalleryStatus.txt"
  __gallerytabular.html: "/GalleryTabular.html"
  __gallerymatplotlibplots.html: "/GalleryMatplotlibPlots.html"
  __optionsfortrackers.html: "/OptionsForTrackers.html"
  __galleryr.html: "/GalleryR.html"
  __gallerybokeh.html: "/GalleryBokeh.html"
  __galleryspecial.html: "/GallerySpecial.html"
  __gallerypdplot.html: "/GalleryPDPlot.html"
  __roles.html: "/Roles.html"
  ___sources__reference.txt: "/_sources/Reference.txt"
  ___sources__gallerytables.txt: "/_sources/GalleryTables.txt"
  __trackers.html: "/Trackers.html"
  ___sources__transformations.txt: "/_sources/Transformations.txt"
  __trackersql.html: "/TrackerSQL.html"
  __galleryuser.html: "/GalleryUser.html"
  __gallerygallery.html: "/GalleryGallery.html"
  ___sources__gallerylineplots.txt: "/_sources/GalleryLinePlots.txt"
  ___sources__galleryslideshowplot.txt: "/_sources/GallerySlideShowPlot.txt"
  ___sources__galleryggplot.txt: "/_sources/GalleryGGPlot.txt"
  __galleryseabornscatterplots.html: "/GallerySeabornScatterPlots.html"
  ___sources__galleryrplots.txt: "/_sources/GalleryRPlots.txt"
  __tutorial6demo.html: "/Tutorial6Demo.html"
  ___sources__galleryseaborndensityplots.txt: "/_sources/GallerySeabornDensityPlots.txt"
  __tutorial7.html: "/Tutorial7.html"
  ___sources__usecase.txt: "/_sources/UseCase.txt"
  ___sources__gallerymatrices.txt: "/_sources/GalleryMatrices.txt"
  ___sources__introduction.txt: "/_sources/Introduction.txt"
  ___sources__galleryseabornheatmapplots.txt: "/_sources/GallerySeabornHeatmapPlots.txt"
  ___sources__galleryhistograms.txt: "/_sources/GalleryHistograms.txt"
  ___sources__glossary.txt: "/_sources/Glossary.txt"
  ___sources__datatypes.txt: "/_sources/DataTypes.txt"
  ___sources__gallerybarplots.txt: "/_sources/GalleryBarplots.txt"
  __tutorial9.html: "/Tutorial9.html"
  ___sources__gallerydataframe.txt: "/_sources/GalleryDataframe.txt"
  ___sources__tutorial8.txt: "/_sources/Tutorial8.txt"
  __galleryseabornboxplots.html: "/GallerySeabornBoxPlots.html"
  ___sources__galleryseaborn.txt: "/_sources/GallerySeaborn.txt"
  __galleryvenn.html: "/GalleryVenn.html"
  ___sources__gallerypieplots.txt: "/_sources/GalleryPiePlots.txt"
  __gallerylegends.html: "/GalleryLegends.html"
  ___sources__galleryscatterplots.txt: "/_sources/GalleryScatterPlots.txt"
  ___sources__server.txt: "/_sources/Server.txt"
  __transformer.html: "/Transformer.html"
  __tutorial1.html: "/Tutorial1.html"
  ___sources__trackersold.txt: "/_sources/TrackersOld.txt"
  ___sources__overview.txt: "/_sources/Overview.txt"
  __tutorial3.html: "/Tutorial3.html"
  __tutorial2.html: "/Tutorial2.html"
  __tutorial5.html: "/Tutorial5.html"
  __tutorial10.html: "/Tutorial10.html"
  __tutorial6.html: "/Tutorial6.html"
  __tutorial4.html: "/Tutorial4.html"
  __tutorial15.html: "/Tutorial15.html"
  __tutorial12.html: "/Tutorial12.html"
  __tutorial14.html: "/Tutorial14.html"
  __tutorial1demo.html: "/Tutorial1Demo.html"
  __tutorial2demo.html: "/Tutorial2Demo.html"
  __tutorial16.html: "/Tutorial16.html"
  __tutorial3demo.html: "/Tutorial3Demo.html"
  __tutorial4demo.html: "/Tutorial4Demo.html"
  __tutorial5demo.html: "/Tutorial5Demo.html"
  ___sources__tutorials.txt: "/_sources/Tutorials.txt"
  ___sources__utilities.txt: "/_sources/Utilities.txt"
  ___sources__running.txt: "/_sources/Running.txt"
  ___sources__advanced.txt: "/_sources/Advanced.txt"
  ___sources__background.txt: "/_sources/Background.txt"
  __tutorial11.html: "/Tutorial11.html"
  ___sources__complexdocuments.txt: "/_sources/ComplexDocuments.txt"
  ___sources__unicode.txt: "/_sources/Unicode.txt"
  __longlabels.html: "/LongLabels.html"
  ___sources__tracker.txt: "/_sources/Tracker.txt"
  __genelists.html: "/GeneLists.html"
  ___sources__tipstricks.txt: "/_sources/TipsTricks.txt"
  ___sources__examples.txt: "/_sources/Examples.txt"
  __genomeinformatics2014example.html: "/GenomeInformatics2014Example.html"
  ___sources__roadmap.txt: "/_sources/Roadmap.txt"
  ___sources__datamapping.txt: "/_sources/DataMapping.txt"
  ___sources__faq.txt: "/_sources/FAQ.txt"
  __renderer.html: "/Renderer.html"
  ___sources__test.txt: "/_sources/Test.txt"
  ___sources__developing.txt: "/_sources/Developing.txt"
  __plotter.html: "/Plotter.html"
  __testexceptions.html: "/TestExceptions.html"
  __galleryoptions.html: "/GalleryOptions.html"
  ___sources__galleryconfig.txt: "/_sources/GalleryConfig.txt"
  __gallerybokehscatterplot.html: "/GalleryBokehScatterPlot.html"
  ___sources__errors.txt: "/_sources/Errors.txt"
  __gallerybokehboxplot.html: "/GalleryBokehBoxPlot.html"
  __gallerybokehbarplot.html: "/GalleryBokehBarPlot.html"
  ___sources__gallerydebug.txt: "/_sources/GalleryDebug.txt"
  ___sources__renderers.txt: "/_sources/Renderers.txt"
  ___sources__gallerytabular.txt: "/_sources/GalleryTabular.txt"
  ___sources__gallerymatplotlibplots.txt: "/_sources/GalleryMatplotlibPlots.txt"
  ___sources__optionsfortrackers.txt: "/_sources/OptionsForTrackers.txt"
  ___sources__galleryr.txt: "/_sources/GalleryR.txt"
  ___sources__gallerybokeh.txt: "/_sources/GalleryBokeh.txt"
  ___sources__galleryspecial.txt: "/_sources/GallerySpecial.txt"
  ___sources__gallerypdplot.txt: "/_sources/GalleryPDPlot.txt"
  ___static__report_directive__testcases_largematrix.code: "/_static/report_directive/TestCases_LargeMatrix.code"
  ___static__report_directive__trackers_getsinglevalue.code: "/_static/report_directive/Trackers_getSingleValue.code"
  ___sources__roles.txt: "/_sources/Roles.txt"
  ___sources__trackers.txt: "/_sources/Trackers.txt"
  ___sources__trackersql.txt: "/_sources/TrackerSQL.txt"
  ___sources__galleryuser.txt: "/_sources/GalleryUser.txt"
  ___sources__gallerygallery.txt: "/_sources/GalleryGallery.txt"
  ___sources__galleryseabornscatterplots.txt: "/_sources/GallerySeabornScatterPlots.txt"
  ___sources__tutorial6demo.txt: "/_sources/Tutorial6Demo.txt"
  ___sources__tutorial7.txt: "/_sources/Tutorial7.txt"
  __testuser.html: "/TestUser.html"
  ___sources__tutorial9.txt: "/_sources/Tutorial9.txt"
  ___sources__galleryseabornboxplots.txt: "/_sources/GallerySeabornBoxPlots.txt"
  ___sources__galleryvenn.txt: "/_sources/GalleryVenn.txt"
  ___sources__gallerylegends.txt: "/_sources/GalleryLegends.txt"
  ___sources__transformer.txt: "/_sources/Transformer.txt"
  ___sources__tutorial1.txt: "/_sources/Tutorial1.txt"
  ___sources__tutorial3.txt: "/_sources/Tutorial3.txt"
  ___sources__tutorial2.txt: "/_sources/Tutorial2.txt"
  ___sources__tutorial5.txt: "/_sources/Tutorial5.txt"
  ___sources__tutorial10.txt: "/_sources/Tutorial10.txt"
  ___sources__tutorial6.txt: "/_sources/Tutorial6.txt"
  ___sources__tutorial4.txt: "/_sources/Tutorial4.txt"
  ___sources__tutorial15.txt: "/_sources/Tutorial15.txt"
  ___sources__tutorial12.txt: "/_sources/Tutorial12.txt"
  ___sources__tutorial14.txt: "/_sources/Tutorial14.txt"
  ___sources__tutorial1demo.txt: "/_sources/Tutorial1Demo.txt"
  ___sources__tutorial2demo.txt: "/_sources/Tutorial2Demo.txt"
  ___sources__tutorial16.txt: "/_sources/Tutorial16.txt"
  ___sources__tutorial3demo.txt: "/_sources/Tutorial3Demo.txt"
  ___sources__tutorial4demo.txt: "/_sources/Tutorial4Demo.txt"
  ___sources__tutorial5demo.txt: "/_sources/Tutorial5Demo.txt"
  ___sources__tutorial11.txt: "/_sources/Tutorial11.txt"
  ___sources__longlabels.txt: "/_sources/LongLabels.txt"
  ___sources__genelists.txt: "/_sources/GeneLists.txt"
  ___sources__genomeinformatics2014example.txt: "/_sources/GenomeInformatics2014Example.txt"
  ___sources__renderer.txt: "/_sources/Renderer.txt"
  ___sources__plotter.txt: "/_sources/Plotter.txt"
  ___sources__testexceptions.txt: "/_sources/TestExceptions.txt"
  ___sources__galleryoptions.txt: "/_sources/GalleryOptions.txt"
  ___sources__gallerybokehscatterplot.txt: "/_sources/GalleryBokehScatterPlot.txt"
  ___sources__gallerybokehboxplot.txt: "/_sources/GalleryBokehBoxPlot.txt"
  ___sources__gallerybokehbarplot.txt: "/_sources/GalleryBokehBarPlot.txt"
  ___sources__testuser.txt: "/_sources/TestUser.txt"
