#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    CGATReport - Report generator based on Sphinx
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    :copyright: Copyright 2009 by Andreas Heger
    :license: BSD, see LICENSE for details.
"""

import sys

if __name__ == '__main__':
    from CGATReport.get import main
    sys.exit(main(sys.argv))
